services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.7.1
    command: start-dev --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USER:-admin}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}
    volumes:
      - ./src/main/resources/keycloak:/opt/keycloak/data/import
    ports:
      - "${KEYCLOAK_PORT:-8080}:8080"